name: Running Action- tidy_hobo_sticr
on:
  workflow_dispatch:
    inputs:
      PAYLOAD:
        description: 'Payload'
        required: false
jobs:
  run_docker_image:
    runs-on: ubuntu-latest
    container: ghcr.io/faasr/github-actions-tidyverse
    env:
      MY_GITHUB_ACCOUNT_TOKEN: ${{ secrets.MY_GITHUB_ACCOUNT_TOKEN }}
      MY_MINIO_BUCKET_ACCESS_KEY: ${{ secrets.MY_MINIO_BUCKET_ACCESS_KEY }}
      MY_MINIO_BUCKET_SECRET_KEY: ${{ secrets.MY_MINIO_BUCKET_SECRET_KEY }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SECRET_PAYLOAD: '{}'
      PAYLOAD: '{"FunctionList":["faasr_tidy_hobo_sticr"],"FunctionInvoke":"faasr_tidy_hobo_sticr","FunctionGitHubRepo":"nirali112/sticr-functions","FunctionGitHubBranch":"main","FunctionGitHubPath":".","FunctionGitHubPackage":["devtools","remotes"],"FunctionCRANPackage":["dplyr","readr"],"ComputeServers":{"my-github-actions":{"FaaSType":"GitHubActions","ActionTimeout":1000}},"DataStores":{"my-minio":{"FaaSType":"minio","Endpoint":"play.min.io","AccessKey":"${{ secrets.MY_MINIO_BUCKET_ACCESS_KEY }}","SecretKey":"${{ secrets.MY_MINIO_BUCKET_SECRET_KEY }}","Bucket":"faasr"}}}'
    steps:        
    - name: run Rscript
      run: |
        cd /action
        Rscript faasr_start_invoke_github-actions.R
